### ISSUE TITLE
Error running docker compose 

### ISSUE THREAD

**Issue by lucasbarros** [B2W-BIT/restQL-http#34]
I'm getting an error trying to run the docker compose.
Seems that the restQL application can't access the mongodb container.

`restql_1   | INFO: Exception in monitor thread while connecting to server mongodb:27017`

**Comment by Light-Gao** [comment]
I think you should have a look on stackoverflow.com or put a question on that site. Not here. Mostly, it's your environment issue.

**Comment by lucasbarros** [comment]
@Light-Gao thanks for the response, but i think that i was not clear on my question. I try to run the docker [compose-compose.yml](https://github.com/B2W-BIT/restQL-server/blob/master/docker-compose.yml) that existis in repo, and it doesn't work for me. 

I realized that the configuration was not correct  and fix it exporting the db port. 

Before:
```
mongodb:
    image: mongo:3.4
    network_mode: host
```

After:
```
mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017
```

**Comment by Light-Gao** [comment]
According to that compose file you linked ,  indeed, it would not work. Since service restql and mongodb are not in the same docker network. Service restql would join a default docker bridge network without any configuration in compose file on network section, but mongodb share the same network with host, which applied by "network_mode: host". Thus, in the restql section, the mongodb url(`mongodb:27017`) won't work.  
You add port mapping section by "ports: "27017:27017", of course, this would work with the mongodb url(`mongodb:27017`) in restql section. BUT it's not what you did to make this work. Because you did not apply any network configuraion neither, which means service mongodb would join the default docker bridge network too as service restql did above. This is the reason why `mongodb:27017` works.  

I think maybe you should put a PR on that repo, or I will.
